language: node_js
node_js:
  - 4
  - 5
  - 6
os:
  - linux
  - centos
  - macosx
  - windows
env:
  - NODE_ENV=nightwatch
before_script:
  - sleep 3
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.2.6 mongodb-org-server=3.2.6 mongodb-org-shell=3.2.6 mongodb-org-mongos=3.2.6 mongodb-org-tools=3.2.6
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version
  - npm i -g nsp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - 'selenium-standalone start 2>&1 &'
  - sleep 3
script:
  - npm test
after_script:
  - nsp check
#services: mongodb
notifications:
  slack: meanstackjs:YtrF35Q7mPqPW5y6NHyDNvkh
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f8affb0a488ea5f5b7c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


language: node_js 
node_js: 
    node services:mongodb 
    addons: 
        apt: 
          sources:
            ubuntu-toolchain-r-test packages:g++-4.8 env:CXX=g++-4.8

