language: node_js
node_js:
  - "0.10.26"
  - 4
  - 5
os:
  - linux
  - centos
  - macosx
  - windows
matrix:
  allow_failures:
    - node_js: 5
env:
  - NODE_ENV=nightwatch
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i bower
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - selenium-standalone start
script:
  - npm test
services: mongodb
