language: node_js
node_js:
  - "0.10.26"
  - 4
  - 5
os:
  - linux
  - centos
  - macosx
  - windows
env:
  - NODE_ENV=nightwatch
before_script:
  - npm i -g nsp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - 'selenium-standalone start 2>&1 &'
  - sleep 3
script:
  - npm test
after_script:
  - nsp check
services: mongodb

